fix(compiler): removing duplicate string when interpolate
winglang/wing pull request #1043
Opened 2023-01-04 19:44 UTC by marciocadev

When interpolate a string with more than one variable, all variables except the last one are duplicated

I create a simple validation on string parser file to remove the duplicated value

Please review this solution carefully as I do not program in Rust, but when I run the current test with this command
```bash
$ npx nx dev -- wing/examples/tests/valid/expressions_string_interpolation.w 
```
the resulting file was created correctly and can be found in the folder `wing/examples/tests/valid/expressions_string_interpolation.w.out/preflight.js`

Closes #1041 

*By submitting this pull request, I confirm that my contribution is made under the terms of the 
[Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

2023-01-04 20:35 UTC, MarkMcCulloh requested changes
Good catch! Now I have to wonder if this was ever somehow accidentally working 😅.
Your change does work, but I think with a slight tweak to the original logic it can work as expected. See comments.

Also, the snapshot tests need to be updated locally by running `npx nx test hangar`

2023-01-04 20:35 UTC, MarkMcCulloh commented on libs/wingc/src/parser.rs
>  						if interpolation_start != last_start {
```suggestion
						if interpolation_start >= last_end
```

2023-01-04 20:35 UTC, MarkMcCulloh commented on libs/wingc/src/parser.rs
> +							parts.push(InterpolatedStringPart::Static(removing_duplication,));
```suggestion
							parts.push(InterpolatedStringPart::Static(
								str::from_utf8(&self.source[last_end..interpolation_start])
									.unwrap()
									.into(),
							));
```

2023-01-04 20:50 UTC, marciocadev commented
Whit this changes I remove the `last_start` variable too

2023-01-04 21:49 UTC, marciocadev commented
@MarkMcCulloh I made some changes but this break the cool_string example, I will explore a little more to resolve this

2023-01-05 09:05 UTC, eladb requested changes
Can we add a test for this.

@MarkMcCulloh can you provide some guidance?

2023-01-05 13:40 UTC, marciocadev commented
I adding two test string on `expressions_string_interpolation.w` and run `npx nx test hangar`

Is this how we test it?

2023-01-05 13:49 UTC, eladb commented
> I adding two test string on `expressions_string_interpolation.w` and run `npx nx test hangar`
> 
> 
> 
> Is this how we test it?
> 
> 

LGTM! 🙏

2023-01-05 14:10 UTC, MarkMcCulloh commented
The changes look good! I just noticed that this PR is opened from a fork. Currently, our workflows require changes to come from branches on this repo so a new PR will need to be created. As a org member, you have the permissions to do this, but if you'd like I can take care of moving your commits to a new branch since you already made the lovely changes. 
Let me know if you could like some help @marciocadev

2023-01-05 14:13 UTC, eladb commented
Here's a [live example](https://youtu.be/kbl-SC3FaBU?t=4061) of this bug!

2023-01-05 16:35 UTC, marciocadev commented
> The changes look good! I just noticed that this PR is opened from a fork. Currently, our workflows require changes to come from branches on this repo so a new PR will need to be created. As an org member, you have the permissions to do this, but if you'd like I can take care of moving your commits to a new branch since you already made the lovely changes. Let me know if you could like some help @marciocadev

Hi @MarkMcCulloh I tried to send it directly but it's giving me a 403 error, even though I put the parsonal access token as password

2023-01-05 16:47 UTC, closed without merging