feat: wing test
winglang/wing pull request #1161
Opened 2023-01-15 23:04 UTC by eladb

A simple testing facility for Wing applications:

    wing test ENTRYPOINT.w

Will execute all `cloud.Function`s named `test` or start with `test:` (e.g. `test: bucket is cool`) inside a simulator.

Each test will be executed in sequence inside a separate instance of the simulator, thereby creating an isolated environment between tests (nice!).

A new testing API was added to the `testing.Simulator` class and includes: `listTests()`, `runTest()`, `runAllTests()`.

*By submitting this pull request, I confirm that my contribution is made under the terms of the 
[Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

2023-01-15 23:05 UTC, eladb commented on apps/wing/src/index.ts
> +    .description("Compiles a Wing program and runs all functions with the word 'test' in their IDs")
update to `test` and `test:`

2023-01-15 23:10 UTC, ekeren commented
Awesome!!!

Do you mind adding a simple example in the docs?

2023-01-16 07:02 UTC, eladb commented on libs/wingsdk/test/testing/simulator.test.ts
> +        "await this.bucket.put('hello', 'world');",
Indent

2023-01-16 07:02 UTC, eladb commented on libs/wingsdk/test/testing/simulator.test.ts
> +    );
Indent

2023-01-17 21:09 UTC, Chriscbr requested changes
E2E test snapshots are missing

2023-01-18 10:28 UTC, Chriscbr approved these changes

2023-01-18 11:24 UTC, eladb commented on libs/wingsdk/src/testing/simulator.ts
> +   */
Perhaps...

2023-01-18 11:24 UTC, merged