feat(sdk): updated cloud.Function runtime to nodejs18.x
winglang/wing pull request #2256
Opened 2023-04-24 14:08 UTC by garysassano

Closes https://github.com/winglang/wing/issues/2134

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

2023-04-24 16:30 UTC, garysassano commented
Hurray! :satisfied:

2023-04-24 18:51 UTC, revitalbarletz commented
Great job @garysassano! So proud of you :)

2023-04-25 16:10 UTC, hasanaburayyan requested changes

2023-04-25 16:10 UTC, hasanaburayyan commented on .devcontainer/devcontainer.json
> +{
This should not be commited to repo

2023-04-25 18:16 UTC, garysassano commented on .devcontainer/devcontainer.json
> +{
Fixed that.

2023-04-25 20:50 UTC, Chriscbr approved these changes

2023-04-26 12:56 UTC, hasanaburayyan approved these changes

2023-04-26 13:24 UTC, merged