fix(docs): improve readme "why a language"
winglang/wing pull request #2322
Opened 2023-04-30 15:32 UTC by eladb

Fixes #2181

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

2023-04-30 15:51 UTC, ShaiBer requested changes
I think that it's a step in the right direction and makes the readme shorter and more exact.
It doesn't answer all the feedback that arose from the Reddit post though because:
1. There is no direct comparison of the same code in Wing and in other languages/frameworks.
2. There is no clear statement of exactly what we can do with Wing that cannot be done with a library/compiler extension, and why. BTW, I think this part may be long and too technical for most, so maybe best to put as an FAQ topic and link to it

2023-04-30 15:51 UTC, ShaiBer commented on README.md
> +The `cloud.Bucket`, `cloud.Counter` and `cloud.Bucket` are *preflight objects*. They represent
```suggestion
The `cloud.Queue`, `cloud.Counter` and `cloud.Bucket` are *preflight objects*. They represent
```

2023-04-30 15:51 UTC, ShaiBer commented on README.md
> +cloud infrastructure resources. When compiled to AWS, a Terraform file will be produced with the AWS implementation
I don't want it to sound like we are an AWS shop

```suggestion
cloud infrastructure resources. When compiled to a specific cloud provider, such as AWS, a Terraform file will be produced with the provider's implementation
```

2023-04-30 16:10 UTC, eladb commented
> There is no clear statement of exactly what we can do with Wing that cannot be done with a library/compiler extension

I thought this is that statement:

"In existing languages, where there is no way to distinguish between multiple execution phases, it is impossible to naturally represent this idea that an object has methods that can only be executed from within a specific
execution phase."

No?

2023-04-30 16:21 UTC, ShaiBer commented
> I thought this is that statement:
> 
> "In existing languages, where there is no way to distinguish between multiple execution phases, it is impossible to naturally represent this idea that an object has methods that can only be executed from within a specific execution phase."
> 
> No?

I don't think it will be clear enough to most readers. Also, it doesn't explain why it cannot be done by other means that are not a language (there are some attempts at similar things by others, like Pulumi and we don't explain where they hit a wall that we don't )

2023-05-01 03:03 UTC, Chriscbr commented on README.md
> +execution phase.
(Optional)
```suggestion
called from inflight scopes. In existing languages, where there is no way to distinguish between multiple execution phases,
it is impossible to naturally represent this idea that an object has methods that can only be executed from within a specific
execution phase in a type-safe manner.
```

or

```suggestion
called from inflight scopes. In existing languages, where there is no way to distinguish between multiple execution phases in the type system,
it is impossible to naturally represent this idea that an object has methods that can only be executed from within a specific
execution phase.
```

2023-05-01 03:19 UTC, Chriscbr commented
> Also, it doesn't explain why it cannot be done by other means that are not a language (there are some attempts at similar things by others, like Pulumi and we don't explain where they hit a wall that we don't )

Maybe we can include a nod to how execution phases as a first-class citizen/concept means your IaC code becomes more composable and reusable, or how it enables resource to infer IAM policies automatically? I could also see some of this being left for the tutorial or getting started guide

2023-05-01 16:59 UTC, ShaiBer commented
> > There is no clear statement of exactly what we can do with Wing that cannot be done with a library/compiler extension
> 
> I thought this is that statement:
> 
> "In existing languages, where there is no way to distinguish between multiple execution phases, it is impossible to naturally represent this idea that an object has methods that can only be executed from within a specific execution phase."
> 
> No?

I like it

2023-05-01 17:02 UTC, ShaiBer approved these changes
Approve, and would like to see your suggestion for making the message even more clear added later as well

2023-05-01 17:38 UTC, merged