fix(sdk): bucket event notification fix
winglang/wing pull request #2463
Opened 2023-05-09 15:35 UTC by tsuf239

fixes: https://github.com/winglang/wing/issues/2308

apparently, it's a known issue while using terraform- 
 and is fixed by keeping only s3BucketNotification per bucket, and adding an id to each one of the s3BucketNotification's topics.

<img width="1123" alt="image" src="https://github.com/winglang/wing/assets/39455181/beaeeeeb-acf4-4be9-8ba5-1ae1c0493929">
(`examples/tests/valid/bucket_events.w` compilation and appliance output)

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

2023-05-10 07:27 UTC, eladb commented
@tsuf239 PR title should for "fix" should describe the problem being fixed (see [PR tips](https://docs.winglang.io/contributors/pull_requests)).

In this case, I would change it to:

```
fix(sdk): unable to add multiple bucket notifications
```

2023-05-10 07:29 UTC, eladb commented on libs/wingsdk/src/target-tf-aws/bucket.ts
> +  private notificationDependencies: ITerraformDependable[] = [];
```suggestion
  private readonly notificationTopics: S3BucketNotificationTopic[] = [];
  private readonly notificationDependencies: ITerraformDependable[] = [];
```

2023-05-10 07:29 UTC, eladb commented on libs/wingsdk/src/target-tf-aws/bucket.ts
> +      new S3BucketNotification(this, `S3Object_notifier`, {
```suggestion
      new S3BucketNotification(this, `S3BucketNotification`, {
```

2023-05-10 07:30 UTC, eladb requested changes
Please add a test

2023-05-14 07:56 UTC, tsuf239 commented
> Please add a test

Relevant tests were edited :)

2023-05-15 14:12 UTC, Chriscbr approved these changes

2023-05-15 15:04 UTC, merged