fix(compiler): fix panic when passing unknown keywords or wrong number of args
winglang/wing pull request #2465
Opened 2023-05-09 15:56 UTC by attias

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

2023-05-09 19:19 UTC, MarkMcCulloh commented on libs/wingc/src/type_check.rs
> +							return self.expr_error(exp, format!("Expected 0 named arguments when instantiating \"{}\"",
```suggestion
							return self.expr_error(exp, format!("Expected named arguments when instantiating \"{}\"",
```

2023-05-09 19:19 UTC, MarkMcCulloh commented on libs/wingc/src/type_check.rs
> +							min_args, pos_args_count, type_
```suggestion
							"Expected {} arguments, but got {} when instantiating \"{}\"",
							min_args, pos_args_count, type_
```

2023-05-09 19:19 UTC, MarkMcCulloh commented on libs/wingc/src/type_check.rs
> +							"Expected {} required positional arguments but got {}",
```suggestion
							"Expected {} arguments but got {}",
```

2023-05-09 19:19 UTC, MarkMcCulloh commented on libs/wingc/src/type_check.rs
> +							return self.expr_error(exp, format!("Expected 0 named arguments for func at {}", exp.span().to_string()
```suggestion
							return self.expr_error(exp, format!("Expected named arguments"
```

2023-05-09 19:19 UTC, MarkMcCulloh commented on libs/wingc/src/type_check.rs
> +						return self.expr_error(exp, format!("No named arguments expected"));
```suggestion
						return self.expr_error(exp, format!("Unexpected named arguments"));
```

2023-05-09 22:43 UTC, eladb commented on examples/tests/invalid/class.w
> +// ^^^^^^^^^ Expected 1 required positional arguments but got 0 when instantiating "C5"
```suggestion
// ^^^^^^^^^ Expected 1 positional arguments but got 0
```

2023-05-09 22:44 UTC, eladb commented on examples/tests/invalid/class.w
>  // ^^^^^^^^^ Expected 0 arguments but got 1 when instantiating "C2"
```suggestion
// ^^^^^^^^^ Expected 0 argument(s) but got 1
```

2023-05-10 07:25 UTC, eladb commented on examples/tests/invalid/class.w
> +// ^^^^^^^^^ Expected 0 named arguments when instantiating \\"C4\\"
```suggestion
// ^^^^^^^^^ Expected 0 named argument(s)"
```

2023-05-10 07:31 UTC, eladb requested changes
@revitalbarletz can you please help with this?

2023-05-11 08:45 UTC, attias commented
@eladb please review

2023-05-16 09:43 UTC, yoav-steinberg commented on examples/tests/invalid/class.w
> +new C5("hello", foo: "bar");
Should we also add tests for the modified logic in functions calls (not only class instantiation)?

2023-05-23 08:36 UTC, eladb approved these changes

2023-05-29 17:32 UTC, eladb approved these changes

2023-05-29 17:33 UTC, eladb approved these changes

2023-05-29 18:50 UTC, merged