feat(compiler): add nil
winglang/wing pull request #2627
Opened 2023-05-22 19:32 UTC by hasanaburayyan

Adds support for nil assignment to optional types

As described: https://github.com/winglang/wing/issues/436

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

2023-05-22 22:32 UTC, eladb approved these changes
Nice!

2023-05-22 22:32 UTC, eladb commented on libs/wingc/src/jsify.rs
> +        Literal::Nil => "null".to_string(),
```suggestion
        Literal::Nil => "undefined".to_string(),
```

2023-05-22 23:08 UTC, Chriscbr requested changes

2023-05-23 15:18 UTC, Chriscbr commented on examples/tests/invalid/nil.w
> +
Got it. I feel like nil types is something we should avoid in the language if there isn't a real world use case for it (minimize language surface area etc etc.), but seeing as `nil` is indeed a type in the spec and @eladb has already blessed this PR, I can only assume he's in favor of it, so let's try it out. 🙂

2023-05-23 15:18 UTC, Chriscbr approved these changes

2023-05-23 16:59 UTC, merged

2023-05-23 22:45 UTC, eladb commented on examples/tests/invalid/nil.w
> +
@hasanaburayyan I think that there was a mixup in the spec (we need to fix it). @Chriscbr got it right -- `nil` is not a type, it's a value that can be assigned to any optional to represent "lack of value". But it shouldn't be possible to use it as a type (e.g. (`let x: nil`)).