chore(docs): generate fewer headings to improve indexing
winglang/wing pull request #3138
Opened 2023-06-28 20:21 UTC by Chriscbr

Attempt to address #2710, along with some other tweaks to generated docs

## Checklist

- [ ] Title matches [Winglang's style guide](https://docs.winglang.io/contributing/pull_requests#how-are-pull-request-titles-formatted)
- [ ] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

2023-06-28 21:02 UTC, MarkMcCulloh approved these changes

2023-06-28 21:04 UTC, Chriscbr commented on apps/jsii-docgen/src/docgen/render/markdown-render.ts
> -    const optionality = prop.optional ? "Optional" : "Required";
err, yeah I should add this back somehow.

2023-06-29 07:46 UTC, eladb requested changes

2023-06-29 07:46 UTC, eladb commented on docs/docs/04-standard-library/01-cloud/api-reference.md
> +**<code>connect</code>**
Does this mean that it is now impossible to link to a specific method?

Can we leave the anchors?

2023-07-12 14:55 UTC, closed without merging