feat(console): sync console theme color with the vs code theme
winglang/wing pull request #3805
Opened 2023-08-14 10:33 UTC by polamoros

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

2023-08-15 08:46 UTC, amielpb commented
Awesome! can the map view elemnts change color as well?

2023-08-16 09:21 UTC, polamoros commented
> Awesome! can the map view elemnts change color as well?

Sure! If we change the map colors, I would only change the node title background. I think changing the nodes background as well can be too much

https://github.com/winglang/wing/assets/5547636/0a787216-8c10-48d8-b42b-7d1020c85c9d

2023-08-17 08:50 UTC, ainvoner requested changes

2023-08-17 09:02 UTC, polamoros commented on apps/vscode-wing/src/console/console-manager.ts
> +          const t = "${Date.now()}";
Exactly, otherwise the iframe will not be rerendered, and the theme color will not change.

I'm adding a comment to make it clear.

2023-08-17 09:02 UTC, polamoros commented on apps/wing-console/console/design-system/src/theme-provider.tsx
> +export const CUSTOMIZABLE_COLOR = "customizable-color";
maybe `USE_CUSTOM_COLOR` ?

2023-08-17 10:34 UTC, polamoros commented on apps/wing-console/console/design-system/src/theme-provider.tsx
> +export const CUSTOMIZABLE_COLOR = "customizable-color";
Renamed to `USE_EXTERNAL_THEME_COLOR`

2023-08-17 10:35 UTC, ainvoner approved these changes

2023-08-17 11:10 UTC, merged