chore(sdk): running the sdk spec tests action before the build
winglang/wing pull request #3850
Opened 2023-08-17 10:23 UTC by tsuf239

Running the sdk spec tests action after pushing to main

## Checklist

- [x] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

2023-08-21 15:44 UTC, MarkMcCulloh requested changes

2023-08-21 15:44 UTC, MarkMcCulloh commented on .github/workflows/tf-aws-test.yml
> +      - main
In order for this workflow to block the build, you would need to do one of these things:

1. Move this workflow to be a job of the build.yml workflow, making it run in run similar to hangar
2. Make the build workflow wait for this to succeed, probably by checking the github API or finding an action that handles that

(1) is much easier. The problem is that to run it before the build means you cannot install wing normally, so you'll have to use the same mechanism that hangar uses.

2023-08-22 13:55 UTC, MarkMcCulloh requested changes
It's possible that these tests need to instead run inside of hangar so that it can install the dev version of wing, but triggered separately from the existing e2e tests. This would be similar to the benchmark tests.

2023-08-22 13:55 UTC, MarkMcCulloh commented on .github/workflows/tf-aws-test.yml
>    workflow_dispatch: {}
should only need workflow_call

```suggestion
```

2023-08-23 12:26 UTC, tsuf239 commented on .github/workflows/tf-aws-test.yml
>    workflow_dispatch: {}
I'll keep the `release` for now

2023-08-23 12:30 UTC, MarkMcCulloh commented on .github/workflows/tf-aws-test.yml
>            command: npm install -g winglang
When you call this workflow during the build workflow, `npm install -g winglang` will install the latest published version of wing and run it against the not-yet-published version of the SDK tests. This mismatch will work sometimes, but it won't always work if there is a breaking change.

2023-09-12 09:53 UTC, tsuf239 commented
Ready :)

2023-09-12 13:52 UTC, MarkMcCulloh commented on .github/workflows/build.yml
> +    secrets: inherit
Both PR and main branch pushes can make use of a diff-based approach. Ideally turbo should be used to get a good diff. This use case is not well documented and I would be happy to meet on it.

2023-09-12 13:52 UTC, MarkMcCulloh commented on .github/workflows/tf-aws-test.yml
> +          npm install -g ./dist/*-[0-9]*.[0-9]*.[0-9]*.tgz
We should probably try to figure this out, it's very strange

2023-09-12 13:52 UTC, MarkMcCulloh commented on .github/workflows/wing-test.yml
> +            echo "$EOF" >> $GITHUB_OUTPUT
Would it be easier to add these tests to the hangar project?

2023-09-12 13:52 UTC, MarkMcCulloh commented on .github/workflows/build.yml
> +    if: github.event_name == 'pull_request'
Is running this in PRs just for testing? I feel like we'll hit rate limits if we run this in every PR

2023-09-21 12:51 UTC, closed without merging