rfc: iterators
winglang/wing pull request #4037
Opened 2023-08-31 13:31 UTC by Chriscbr

Proposal for a spec update to add support for a dedicated Iterator type in the language.

Closes #4036

## Checklist

- [ ] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [ ] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

2023-09-22 08:52 UTC, eladb requested changes

2023-09-22 08:52 UTC, eladb commented on docs/docs/03-language-reference.md
> +Many types in Wing implement the `Iterator<T>` interface.
```suggestion
Many types in Wing implement the `IIterator<T>` interface.
```

2023-09-22 08:52 UTC, eladb commented on docs/docs/03-language-reference.md
> +interface Iterator<T> {
```suggestion
interface IIterator<T> {
```

2023-09-22 08:52 UTC, eladb commented on docs/docs/03-language-reference.md
> +If an object has a method named `iter()` that returns an `Iterator<T>`, then it will automatically be used by the `for` statement.
Nice!

Should we have an `IIterable<T>` as well?

2023-09-22 08:52 UTC, eladb commented on docs/docs/03-language-reference.md
> +interface Iterator<T> {
Is this compatible with JavaScript? Let's make sure they are seamlessly interoperable

2023-09-25 18:42 UTC, Chriscbr commented on docs/docs/03-language-reference.md
> +interface Iterator<T> {
Sort of. The way it works in JavaScript is a little bit different -- here's a repl session I whipped up that shows how iteration works:

```
$ node
Welcome to Node.js v18.16.0.
Type ".help" for more information.
> let x = [1, 2, 3]
undefined
> let it = x[Symbol.iterator]();
undefined
> it.next()
{ value: 1, done: false }
> it.next()
{ value: 2, done: false }
> it.next()
{ value: 3, done: false }
> it.next()
{ value: undefined, done: true }
```

My thinking was that in Wing we can provide a more ergonomic API for iteration, where you can obtain individual values or check if the iteration is finished directly.

For interop with JavaScript, I was imagining that given a Wing object that implements the `IIterator<T>` API, we could convert it into the corresponding JavaScript iterator so it will still work in JavaScript contexts that expect the JavaScript iteration scheme -- and given any JavaScript iterator, when it's lifted into Wing, we could converted into a form with extra `step()` and `hasNext()` methods so it can be iterated in Wing-idiomatic contexts.

(as I write this down, I realize a POC would be good to do first)

Alternatively, I could see it making sense just to model the JavaScript API directly in Wing and call it a day.

2023-09-26 05:57 UTC, eladb commented on docs/docs/03-language-reference.md
> +interface Iterator<T> {
If the JS API is good enough, I think there's value in aligning to save glue and special casing. We would also want to support generator functions at some points, so there's an interplay with these APIs there as well.

2023-12-28 17:48 UTC, garysassano commented
Keep.

2024-04-16 06:05 UTC, closed without merging