feat(compiler) generate "use strict;"
winglang/wing pull request #4466
Opened 2023-10-08 23:30 UTC by exoego

Closes https://github.com/winglang/wing/issues/2527

## Checklist

- [ ] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [ ] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

2023-10-11 18:05 UTC, Chriscbr requested changes

2023-10-11 18:05 UTC, Chriscbr commented on tools/hangar/__snapshots__/test_corpus/valid/bring_local.test.w_compile_tf-aws.md
It looks like we're adding `"use strict";` to all `preflight.js` and `preflight.*.js` files but we also need to add it to the top of `inflight.*.js` files

2023-10-12 04:23 UTC, exoego commented on tools/hangar/__snapshots__/test_corpus/valid/bring_local.test.w_compile_tf-aws.md
Fixed in https://github.com/winglang/wing/pull/4466/commits/d38cba445dbd24ce2db7183840db5fc6e59d216a and https://github.com/winglang/wing/pull/4466/commits/b5a1368669b8901395845b5973d6539b3f9fc9ac

2023-10-12 11:32 UTC, exoego commented on tools/hangar/__snapshots__/test_corpus/valid/bring_local.test.w_compile_tf-aws.md
I've noticed `function` and `service` generates JS so fixed it
https://github.com/winglang/wing/pull/4466/commits/bcff52b955df04e161eebf06f75422e651b51a59

2023-10-12 21:01 UTC, merged