docs:fixed multiple typos
winglang/wing pull request #4600
Opened 2023-10-19 13:47 UTC by Subash-Lamichhane

## Checklist

- [ ] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [ ] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

Fixed multiple typos of docs folder:

2023-10-19 15:32 UTC, MarkMcCulloh requested changes

2023-10-19 15:32 UTC, MarkMcCulloh commented on docs/docs/04-standard-library/01-cloud/service.md
This needs to be updated in the docstrings in https://github.com/winglang/wing/blob/main/libs/wingsdk/src/cloud/service.ts#L181

2023-10-19 15:32 UTC, MarkMcCulloh commented on docs/docs/04-standard-library/03-std/api-reference.md
Needs to be updated in docstrings in https://github.com/winglang/wing/blob/main/libs/wingsdk/src/std/array.ts#L298

2023-10-19 16:21 UTC, garysassano commented
@eladb What you think about updating stories to correct typos? I remember I did something similar in the past when replacing `Monada` with `Wing` and you asked to revert it.

2023-10-19 16:22 UTC, garysassano commented
@eladb What you think about updating stories to correct typos? I remember I did something similar in the past when replacing `Monada` with `Wing` and you asked to revert those.

2023-10-19 16:26 UTC, Subash-Lamichhane commented on docs/docs/04-standard-library/01-cloud/service.md
I have updated it.

2023-10-22 11:30 UTC, staycoolcall911 approved these changes

2023-10-22 11:53 UTC, merged