feat(sdk): add missing utilities for `fs` module
winglang/wing pull request #4878
Opened 2023-11-10 02:00 UTC by garysassano

Closes #4838

## Checklist

- [x] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

2023-11-11 13:14 UTC, eladb requested changes
i prefer that we retain POSIX terminology here

2023-11-11 13:14 UTC, eladb commented on libs/wingsdk/src/fs/fs.ts
>    public static exists(p: string): boolean {
```suggestion
  public static exists(path: string): boolean {
```

2023-11-11 13:14 UTC, eladb commented on libs/wingsdk/src/fs/fs.ts
>    public static remove(p: string, opts?: RemoveOptions): void {
```suggestion
  public static remove(path: string, opts?: RemoveOptions): void {
```

2023-11-11 13:14 UTC, eladb commented on libs/wingsdk/src/fs/fs.ts
> +  public static isDir(p: string): boolean {
Please check everywhere that the argument matches the docstring

2023-11-11 13:14 UTC, eladb commented on libs/wingsdk/src/fs/fs.ts
> +  public static metadata(p: string): Metadata {
please rename to `stat`

2023-11-11 13:14 UTC, eladb commented on libs/wingsdk/src/fs/fs.ts
> +  public static symlinkMetadata(p: string): Metadata {
please rename to `lstat`

2023-11-11 13:14 UTC, eladb commented on libs/wingsdk/src/fs/fs.ts
> +  public static setPermissions(p: string, permissions: string): void {
please rename to `chmod`

2023-11-11 13:14 UTC, eladb commented on libs/wingsdk/src/fs/fs.ts
> +  public static extension(p: string): string | undefined {
please rename to `extname`

2023-11-11 13:14 UTC, eladb commented on libs/wingsdk/src/fs/fs.ts
> +    type: "file" | "dir" | "junction" = "file"
please use an enum

2023-11-11 13:14 UTC, eladb commented on libs/wingsdk/src/fs/fs.ts
> +        return "File";
```suggestion
        return FileType.File;
```

2023-11-11 13:14 UTC, eladb commented on libs/wingsdk/src/fs/fs.ts
> +      permissions: this._formatPermissions(stats.mode),
```suggestion
      mode: this._formatPermissions(stats.mode),
```

2023-11-11 13:20 UTC, eladb commented on libs/wingsdk/src/fs/fs.ts
> +  public static metadata(p: string): Metadata {
ok, I am okay with the rust terminology, so ignore these comments...

2023-11-11 13:20 UTC, eladb commented on libs/wingsdk/src/fs/fs.ts
> +  public static symlinkMetadata(p: string): Metadata {
ignore

2023-11-11 13:20 UTC, eladb commented on libs/wingsdk/src/fs/fs.ts
> +  public static setPermissions(p: string, permissions: string): void {
ignore

2023-11-11 13:21 UTC, eladb approved these changes
ok, I am okay with the rust terminology, so ignore these comments...
i saw @Chriscbr's comment on the issue.

ship it (with a few tweaks)

2023-11-11 19:53 UTC, merged

2023-11-13 14:43 UTC, Chriscbr commented
Thanks @garysassano !