feat(console): use figma-like controls for the map view
winglang/wing pull request #5433
Opened 2024-01-12 13:19 UTC by skyrpex

On MacOS:

- Move two fingers together to translate the map
- Use pinch gesture to zoom in and out

2024-01-14 15:43 UTC, eladb approved these changes

2024-01-15 11:31 UTC, polamoros commented
Zoom in/ zoomm out is not centering the map anymore.
https://github.com/winglang/wing/assets/5547636/cc27d7ca-7f03-42ce-a9e6-421008a33699

2024-01-15 11:34 UTC, polamoros commented
When is the "out of bounds" message showing up?

https://github.com/winglang/wing/assets/5547636/8f3ec7a8-b5eb-43b2-a1db-49c4b8158904

2024-01-15 11:34 UTC, polamoros requested changes

2024-01-15 11:34 UTC, polamoros commented on apps/wing-console/console/ui/src/ui/zoom-pane.tsx
> +const boundingBoxOverlap = (a: BoundingBox, b: BoundingBox) => {
could you add a comment here?

2024-01-16 09:23 UTC, polamoros approved these changes

2024-01-16 19:45 UTC, Chriscbr commented
🚀 🚀 🚀

2024-01-18 10:05 UTC, merged