feat(sdk): add missing fs.appendFile
winglang/wing pull request #5800
Opened 2024-02-29 05:53 UTC by CJLA

https://github.com/winglang/wing/issues/5392

## Checklist

- [x] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [x] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

2024-02-29 07:55 UTC, eladb approved these changes
Great job! 👏

2024-02-29 14:59 UTC, hasanaburayyan requested changes
@CJLA Great work! Can you please add some unit tests for this? The file you will want to do that in is `libs/wingsdk/test/fs/fs.test.ts` Should be some examples there, once you add that Ill take another look and should be good to ship 👍

2024-02-29 14:59 UTC, hasanaburayyan commented on libs/wingsdk/src/fs/fs.ts
> +   * @param filepath The file path that needs to be written.
```suggestion
   * @param filepath The file path that needs to be appended.
```

2024-02-29 23:55 UTC, CJLA commented
> @CJLA Great work! Can you please add some unit tests for this? The file you will want to do that in is `libs/wingsdk/test/fs/fs.test.ts` Should be some examples there, once you add that Ill take another look and should be good to ship 👍

@hasanaburayyan I'm trying to run the unit tests in `libs/wingsdk/test/fs/fs.test.ts` and get this error.

`Error: Cannot find module '../package.json'
Require stack:
- /Users/christopherjohnson/wing/libs/wingsdk/test/fs/target/test/fs.test.ts.wsim/.wing/ts/src/constants.js
- /Users/christopherjohnson/wing/libs/wingsdk/test/fs/target/test/fs.test.ts.wsim/.wing/ts/src/core/app.js
- /Users/christopherjohnson/wing/libs/wingsdk/test/fs/target/test/fs.test.ts.wsim/.wing/ts/src/core/index.js
- /Users/christopherjohnson/wing/libs/wingsdk/test/fs/target/test/fs.test.ts.wsim/.wing/ts/src/fs/fs.js
- /Users/christopherjohnson/wing/libs/wingsdk/test/fs/target/test/fs.test.ts.wsim/.wing/ts/test/fs/fs.test.js
- /Users/christopherjohnson/wing/[worker eval]`

I think it's looking for `libs/wingsdk/package.json` which I do see in my files. I was able to successfully run the other unit tests I wrote in `examples/tests/sdk_tests/fs/basic.test.w`

2024-03-01 00:12 UTC, hasanaburayyan commented
@CJLA can you confirm what command your using to test, as well as your node version?

2024-03-01 00:18 UTC, CJLA commented
@hasanaburayyan 

`pnpm wing test libs/wingsdk/test/fs/fs.test.ts`
Node v20.11.1

2024-03-03 15:02 UTC, hasanaburayyan commented
@CJLA hmmm what happens if you cd into `libs/wingsdk` and just run `npx vitest fs`

2024-03-04 06:48 UTC, CJLA commented
@hasanaburayyan that worked :thumbsup:

2024-03-04 13:47 UTC, hasanaburayyan approved these changes
@CJLA Great job, thanks so much for sticking it through to get the unit tests in. As well CONGRATS on your first contribution! 🔥 🎉 Looking forward to the next!

2024-03-04 16:29 UTC, merged