fix(console): respect `node.title` in the map view
winglang/wing pull request #6464
Opened 2024-05-13 07:59 UTC by skyrpex

Update the display of node names in the MapView component to show the title if available, falling back to the id if not.

Fixes #6457.

2024-05-13 08:51 UTC, eladb approved these changes
Is there a way to test this?

2024-05-13 09:32 UTC, skyrpex commented
> Is there a way to test this?

We have to revisit the test suite and then we could start adding the tests back. But right now they are just being skipped.

2024-05-13 10:14 UTC, eladb commented
Bummer

On Mon, May 13, 2024 at 12:32 PM Cristian Pallarés ***@***.***>
wrote:

> Is there a way to test this?
>
> We have to revisit the test suite and then we could start adding the tests
> back. But right now they are just being skipped.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/winglang/wing/pull/6464#issuecomment-2107094394>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAESGDF6GB7DZJQ6QD7MQPLZCCCCTAVCNFSM6AAAAABHTVZ6MGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMBXGA4TIMZZGQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-05-13 16:03 UTC, ainvoner commented
@skyrpex just making sure you tested:
display.title, "as", and ID 
for reference:
https://github.com/winglang/wing/pull/6211
https://github.com/winglang/wing/issues/5994

2024-05-13 16:04 UTC, ainvoner requested changes

2024-05-13 16:04 UTC, ainvoner commented on apps/wing-console/console/ui/src/features/map-view.tsx
> +            name={
@skyrpex just making sure you tested:
display.title, "as", and ID 
for reference:
https://github.com/winglang/wing/pull/6211
https://github.com/winglang/wing/issues/5994

2024-05-16 14:39 UTC, ainvoner approved these changes

2024-05-16 14:44 UTC, merged