feat(compiler): punning
winglang/wing pull request #6752
Opened 2024-06-20 06:48 UTC by yoav-steinberg

Fixes #247
Support "punning" in struct literals
```wing
struct Bla {
  a: num;
  b: str;
}
let a = 1;
let b = "bla";
let x = Bla {a, b};
```

## Checklist

- [x] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

2024-06-21 16:31 UTC, Chriscbr requested changes
Looks like a great start - added a few small comments

2024-06-21 16:31 UTC, Chriscbr commented on docs/docs/03-language-reference.md
> +A struct literal initialization may use "punning" syntax:
```suggestion
A struct literal initialization may use "punning" syntax to initialize fields using variables of the same names:
```

2024-06-21 16:31 UTC, Chriscbr commented on examples/tests/invalid/json.test.w
> +{numField, numField};
Perhaps also check for these cases:
```suggestion
// Duplicate field in punned json
let numField = 1;
{numField, numField};
{numField: 5, numField};

// Wrong type when using punning
let bucket = new cloud.Bucket();
Json { bucket };
```

2024-06-21 16:31 UTC, Chriscbr commented on examples/tests/valid/json.test.w
Please add a test that this also works for MutJson

2024-06-21 16:31 UTC, Chriscbr commented on examples/tests/valid/structs.test.w
I wonder if we should support punning for `Map` and `MutMap` as well somehow... it might require some kind of changes to our syntax e.g.

```js
let baz = "value";
let myMap = { foo => "bar", baz };
```

IMO the ideal would be to unify the Map and Json syntaxes and just require a `Map<T>` or `map` annotation when you want a map:

```js
let baz = new cloud.Bucket() as "baz";
let myMap = map { foo: makeBucket(), baz };
```

WDYT? Let me know if I should open a separate issue for this

2024-06-21 17:22 UTC, MarkMcCulloh commented on examples/tests/valid/structs.test.w
+1 for just getting rid of the syntax, here's an existing issue https://github.com/winglang/wing/issues/5700

2024-06-21 17:58 UTC, yoav-steinberg commented on examples/tests/valid/structs.test.w
+1 one for unifying the syntax, perhaps punning will come out of the box then?
What do you say to just make this part of #5700?

2024-06-21 18:01 UTC, Chriscbr commented on examples/tests/valid/structs.test.w
Sounds good 👍

2024-06-21 18:02 UTC, Chriscbr approved these changes

2024-06-21 18:17 UTC, merged

2024-06-23 08:56 UTC, eladb commented
yey!