feat(console): animate tree view items when expanding and collapsing
winglang/wing pull request #6895
Opened 2024-07-11 16:00 UTC by skyrpex

This changeset animates tree view items when expanding and collapsing.

2024-07-11 16:02 UTC, skyrpex commented
https://github.com/winglang/wing/assets/1077520/f7dd5d95-50c6-410a-8a47-ebb3efa0b129

2024-07-12 13:18 UTC, polamoros requested changes

2024-07-12 13:18 UTC, polamoros commented on apps/wing-console/console/design-system/src/headless/tree-item.tsx
> +import { motion, AnimatePresence } from "framer-motion";
```suggestion
import { motion } from "framer-motion";
```

2024-07-12 13:40 UTC, polamoros approved these changes

2024-07-12 13:43 UTC, merged