feat(sdk): adding bucket cors rule
winglang/wing pull request #7058
Opened 2024-08-28 15:44 UTC by tsuf239

Allowing this app: https://github.com/winglang/react-file-upload-example to work, as requested by a potential wing user :)

## Checklist

- [ ] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [ ] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

2024-08-28 16:13 UTC, Chriscbr commented on examples/tests/sdk_tests/bucket/cors.test.w
> +  allowedOrigins:[api.url]
```suggestion
  allowedOrigins: [api.url]
```

2024-08-28 16:17 UTC, Chriscbr commented on examples/tests/sdk_tests/bucket/cors.test.w
> +  };
Is it possible to use `http.fetch` instead? Perhaps like

```suggestion
  let response = http.fetch(
    bucket.signedUrl("hello"),
    method: http.HttpMethod.OPTIONS,
    headers: {
      Origin: api.url,
      "Access-Control-Request-Method": "GET",
    },
  );
  return {
    body: response.body
  };
```

2024-08-28 16:21 UTC, Chriscbr commented on libs/wingsdk/src/cloud/bucket.ts
> +export interface BucketCorsOptions {
One of the build errors is asking for a docstring for this interface

2024-09-09 16:42 UTC, Chriscbr requested changes

2024-09-09 16:42 UTC, Chriscbr commented on packages/@winglang/sdk/src/cloud/bucket.ts
> +  readonly maxAgeSeconds?: Number;
```suggestion
  /**
   * How long the browser should cache preflight request results.
   * @default - 300 seconds
   */
  readonly maxAge?: Duration;
```

2024-09-09 16:42 UTC, Chriscbr commented on packages/@winglang/sdk/src/cloud/bucket.ts
Can we add a `cors: boolean` option to the constructor which defaults to `true`? The `true` setting should be equivalent to adding the following config:

```
{
    allowHeaders: ["*"],
    allowOrigins: ["*"],
    allowMethods: ["DELETE", "GET", "HEAD", "POST", "PUT"],
    exposeHeaders: [],
    maxAge: 0s,
}
```
(these are the same defaults SST uses: https://sst.dev/docs/component/aws/bucket#cors)

2024-09-11 05:25 UTC, closed without merging

2024-09-11 09:11 UTC, tsuf239 commented
@Chriscbr thanks for the addition,
is this PR still needed?